import {
  ALT_LOGO_TAG,
  ALT_SEARCH_ICON_TAG,
  ALT_DELETE_ICON_TAG,
  ALT_EDIT_ICON_TAG,
  ALT_CHECK_ICON_TAG,
  ICON_LOGO,
  ICON_SEARCH,
  ICON_DELETE,
  ICON_EDIT,
  ICON_CHECK,
} from "utils/const/images";
import {
  TEXTAREA_DEFAULT_ROW,
  ATTRIBUTE_TITLE,
  TYPE_SUBMIT,
  TYPE_BUTTON,
  TASK_DATE_FORMAT,
  FORM_VALIDATION_MODE_ONCHANGE,
} from "utils/const/formElements";
import { ERROR_MESSAGE_TASK_TITLE } from "utils/const/errorMessages";
import {
  TASK_FILTER_ALL,
  TASK_FILTER_INCOMPLETED,
  TASK_FILTER_COMPLETED,
} from "./tasks";

export {
  ALT_LOGO_TAG,
  ALT_SEARCH_ICON_TAG,
  ALT_DELETE_ICON_TAG,
  ALT_EDIT_ICON_TAG,
  ALT_CHECK_ICON_TAG,
  ICON_LOGO,
  ICON_SEARCH,
  ICON_DELETE,
  ICON_EDIT,
  ICON_CHECK,
  TEXTAREA_DEFAULT_ROW,
  ATTRIBUTE_TITLE,
  TYPE_SUBMIT,
  TYPE_BUTTON,
  TASK_DATE_FORMAT,
  FORM_VALIDATION_MODE_ONCHANGE,
  ERROR_MESSAGE_TASK_TITLE,
  TASK_FILTER_ALL,
  TASK_FILTER_INCOMPLETED,
  TASK_FILTER_COMPLETED,
};
