import {
  LOGO_ALT_TAG,
  SEARCH_ICON_ALT_TAG,
  DELETE_ICON_ALT_TAG,
  EDIT_ICON_ALT_TAG,
  CHECK_ICON_ALT_TAG,
  NO_TASK_FOUND_ICON_ALT_TAG,
  LOGO_IMG_PATH,
  SEARCH_ICON_PATH,
  DELETE_ICON_PATH,
  EDIT_ICON_PATH,
  CHECK_ICON_PATH,
  NO_TASK_FOUND_ICON_PATH,
} from "utils/const/images";
import {
  TEXTAREA_DEFAULT_ROW,
  TASK_TEXTAREA_NUM_OF_ROW,
  TYPE_BUTTON,
  TYPE_SUBMIT,
  TITLE_FIELD_NAME_ATTRIBUTE,
} from "utils/const/formElements";
import { CARD_PER_PAGE } from "./tasks";
import {
  CUSTOM_ERROR_MESSAGE_TYPE,
  TASK_TITLE_ERROR_MESSAGE,
} from "./errorMessages";

export {
  LOGO_ALT_TAG,
  SEARCH_ICON_ALT_TAG,
  DELETE_ICON_ALT_TAG,
  EDIT_ICON_ALT_TAG,
  CHECK_ICON_ALT_TAG,
  NO_TASK_FOUND_ICON_ALT_TAG,
  LOGO_IMG_PATH,
  SEARCH_ICON_PATH,
  DELETE_ICON_PATH,
  EDIT_ICON_PATH,
  CHECK_ICON_PATH,
  NO_TASK_FOUND_ICON_PATH,
  TEXTAREA_DEFAULT_ROW,
  TASK_TEXTAREA_NUM_OF_ROW,
  TYPE_BUTTON,
  TYPE_SUBMIT,
  CARD_PER_PAGE,
  TITLE_FIELD_NAME_ATTRIBUTE,
  CUSTOM_ERROR_MESSAGE_TYPE,
  TASK_TITLE_ERROR_MESSAGE,
};
