export const ADD_TASK = "ADD_TASK";
export const DELETE_TASK = "DELETE_TASK";
export const MARK_TASK_DONE = "MARK_TASK_DONE";
export const EDIT_TASK = "EDIT_TASK";

export const LOAD_MORE_TASK = "LOAD_MORE_TASK";
export const RESET_VISIBLE_TASK_COUNT = "RESET_VISIBLE_TASK_COUNT";

export const FILTER_TASK = "FILTER_TASK";
export const DECREASE_NUM_OF_VISIBLE_TASK = "DECREASE_NUM_OF_VISIBLE_TASK";
